//WHAT IS AVL TREE?
/*
IT IS A SELF BALANCING BINARY SEARCH TREE. BASICALLY IT IS A BALANCED BINARY TREE.
IN THE BALANCED BINARY TREE, ALL THE LEVELS ARE COMPLETE EXCEPT THE LEAF NODE LEVEL AND ALL THE NODES ARE LEFT INCLINED....MATLAB JIS LEVEL PE BALANCE NHI HAI...YANI KI LAST LEVEL, IN CASE, TOH NODES LEFT MEIN HONE CHAHIYE...RIGHT MEIN NHI.
*/

//WHAT IS BALANCE FACTOR
/*
BALANCE FACTOR OF NODE IS DIFFERENCE BETWEEN RIGHT SUBTREE AND THE LEFT SUBTREE. IN CASE OF AVL TREES, EACH NODE HAS A BALANCE FACTOR OF EITHER 1, 0 OR -1.
*/

//ROTATIONS IN AVL TREES?
/*
WHENEVER IS NODE IS ADDED OR DELETED THEN TO MAKE THE TREE A BALANCED ONE, THERE ARE ROTATIONS IN TREE

1. LL ROTATION: WHEN THE NODE IS INSERTED TO LEFT OF LEFT THEN WE USE THIS ROTATION. BASICALLY, IN THIS CASE THE BALANCE FACTOR OF THE NODES GET DISTURBED WHEN THE NODE IS ADDED, THEREFORE, WE DO A CLOCKWISE ROTATION TO BALANCE THE TREE.
    7                              5
   /                              / \  
  5      -> LL ROTATION ->       4   7
 /
4 

2. RR ROTATION: WHEN THE NODE IS INSERTED TO RIGHT OF RIGHT THEN WE USE THIS ROTATION. BASICALLY, IN THIS CASE THE BALANCE FACTOR OF THE NODES GET DISTURBED WHEN THE NODE IS ADDED, THEREFORE, WE DO A ANTICLOCKWISE ROTATION TO BALANCE THE TREE.
    11                                  15
     \                                 / \  
      15      -> RR ROTATION ->       11  20
       \
        20

3. LR ROTATION: WHEN THE NODE IS INSERTED TO THE LEFT OF RIGHT. THAT MEANS THE NODE IS ADDED TO THE RIGHT OF LEFT SUBTREE. TO BALANCE THE TREE WE HAVE TO GIVE AN ANTICLOCKWISE ROTATION FIRST AND THEN THE CLOCKWISE ROTATION.
    7                                         7                           6
   /                                         /                           / \
  5      -> ANTICLOCKWISE ROTATION ->       6  ->CLOCKWISE ROTATION ->  5   7
   \                                       /                 
    6                                     5 

4. RL ROTATION: WHEN THE NODE IS INSERTED TO THE RIGHT OF LEFT .THAT MEANS THE NODE IS ADDED TO THE LEFT OF RIGHT SUBTREE. TO BALANCE THE TREE WE HAVE TO GIVE AN CLOCKWISE ROTATION FIRST AND THEN THE ANTICLOCKWISE ROTATION.
*/