//ROTATIONS WHEN THERE ARE MULTUIPLE NODES
/*
1. LEFT-LEFT INSERTION: INITAILLY, I HAVE A TREE WHICH IS BALANCED. NOW AFTER THE INSERTION OF A NODE MY TREE GETS IMBALANCED AT SOME OF THE NODES, THEN WITH RESPECT TO THAT FIRST IMBALANCE NODE, FROM THE NODE WHERE THE INSERTION HAPPENS, IF THE BOTH THE FIRST TWO NODES ARE THERE AT THE LEFT THEN IT IS CALLED AS LEFT LEFT INSERTION.
IN THIS CASE WE WILL GIVE A CLOCKWISE ROTATION WITH RESPECT TO THE FIRST IMBALACED NODE.

2. RIGHT-RIGHT INSERION: INITAILLY, I HAVE A TREE WHICH IS BALANCED. NOW AFTER THE INSERTION OF A NODE MY TREE GETS IMBALANCED AT SOME OF THE NODES, THEN WITH RESPECT TO THAT FIRST IMBALANCE NODE, FROM THE NODE WHERE THE INSERTION HAPPENS, IF THE BOTH THE FIRST TWO NODES ARE THERE AT THE RIGHT THEN IT IS CALLED AS RIGHT RIGHT INSERTION.
IN THIS CASE WE WILL GIVE AN ANTICLOCKWISE ROTATION WITH RESPECT TO THE FIRST IMBALACED NODE.

3. LEFT RIGHT INSERITON: IN SUCH CASES FIRST GIVE AN ANTICLOCKWISE ROTATION WITH RESPECT TO CHILD OF FIRST IMBALANCED NODE AND THEN GIVE A CLOCKWISE ROTATION WITH RESPECT TO FIRST IMBALANCED NODE.

4. RIGHT LEFT INSERION: IN SUCH CASES FIRST GIVE AN CLOCKWISE ROTATION WITH RESPECT TO CHILD OF FIRST IMBALANCED NODE AND THEN GIVE AN ANTICLOCKWISE ROTATION WITH RESPECT TO FIRST IMBALANCED NODE.
*/